### ISSUE TITLE
Loader or Transform()

### ISSUE THREAD

**Issue by mens-artis** [automl/trivialaugment#1]
Is there an easy way to make a DataLoader, or for example ImageFolder, or to use something like transforms = [ToTensor(), TrivialAugment()] ? Because, a quick look let me to believe that TrivialAugment(img) is needed for the latter and this is not accepted as a standard torch Transform.

**Comment by SamuelGabriel** [comment]
The usage you propose should work out of the box. You should just change the order to [TrivialAugment(), ToTensor()]. Probably you want to normalise as well. Doesn't that work?

**Comment by mens-artis** [comment]
I tried:
```
import aug_lib
# augmenter = aug_lib.TransformFunction() and
augmenter = aug_lib.TrivialAugment()
data_augmentations = [transforms.ToTensor(), augmenter]
```
but it says augmenter needs an img argument, which is not available here

**Comment by SamuelGabriel** [comment]
Did you use `Compose`? Please try this as augmentation operation `transforms.Compose([TrivialAugment(), ToTensor()])` for your data loader. This should work in my books.

**Comment by mens-artis** [comment]
Yes, it looks like this works. Thank you. Are the random transforms automatically adapted to the image size? And are they applied once, when used with a DataLoader or is a different one used every time for every image?

**Comment by SamuelGabriel** [comment]
They should work with most image sizes out of the box. And, yes, the transform is called anew for each image giving a different augmentation per image.

**Comment by xiaobai-marker** [comment]
> Did you use `Compose`? Please try this as augmentation operation `transforms.Compose([TrivialAugment(), ToTensor()])` for your data loader. This should work in my books.

After I used this method, the losses actually increased in both of my models, why is this?
