### ISSUE TITLE
What is the reason for having 30 bins of possible strengths?

### ISSUE THREAD

**Issue by snarb** [automl/trivialaugment#2]
Hello. Thanks for the work and code. Do not understand why do we need to have 30 bins in the end, why not just to sample augmentation strength  uniformly in the specific intervals? Do we need a granularity? What is the intuinition behind this?

**Comment by SamuelGabriel** [comment]
Hey :) it is actually rather a fragment of previous work. It is standard to do this discretization since AutoAugment. We also included an experiment in the paper, where we found that the exact discretization does not matter much, so I would expect no discretization would be fine too.
