### ISSUE TITLE
TA for Object Detection

### ISSUE THREAD

**Issue by levan92** [automl/trivialaugment#5]
Hi, firstly thank you for sharing this finding, it is really interesting to find that after going one big round, the simple solutions might work the best after all. 

Saw that you all did point out at the end of the paper that TA does not extend well for Object Detection task. Is it possible to share more details regarding this, and what sort of tuning you all did?

**Comment by SamuelGabriel** [comment]
Hi, We tried to use it with the `detectron2` codebase (https://github.com/facebookresearch/detectron2). We used it for COCO-Detection with a Retina Net. We compared it to RandAugment and tuned the maximum strength in TrivialAugment. Somehow, most of the time either it did not matter or RandAugment was even better than TrivialAugment. This was done relatively quickly, though, so take it with a grain of salt. We also had weird results, s.t. TrivialAugment with any maximum strength was weaker than RandAugment with one application (n=1) and a fixed strength m. Very different from our classification results. Could I help you or do you have any further questions?

**Comment by SamuelGabriel** [comment]
Oh and we took care of transformations that change bounding boxes. We did experiments leaving these transformations away completely and changing the bounding boxes along the images. Both did not change the results discussed above.
