### ISSUE TITLE
Do sharpness and auto_contrast do much?

### ISSUE THREAD

**Issue by jfltzngr** [automl/trivialaugment#9]
Hi, 
I'm currently trying to find the perfect trivial augmentation policy for my problem. When I apply the auto_contrast or sharpness at 2 strength levels and i display a few augmentations, i can't tell if there happens anything compared to the original image. I've already tried to rise the minVal but nothing changed. 
Here's a minimal working example
```python
from PIL import Image
import aug_lib

orig_img = Image.open('pizza.jpeg')
aug_lib.set_augmentation_space(augmentation_space='wide_standard_custom', 
                                           num_strengths=2, 
                                           custom_augmentation_space_augs=["auto_contrast" ]) # or sharpness                                                                   
augmenter = aug_lib.TrivialAugment()
for _ in range(4):
    display(augmenter(orig_img))
```

Thanks in advance for your commitment!

Kind regards, 
Johannes

**Comment by SamuelGabriel** [comment]
Hi Johannes,

Sorry for the late answer!

I am not sure tbh. I think, I also saw some augmentations that have little impact. 
You should check the exact pixel values. To me it seems logical that a little amount of auto contrast is (almost) invisible to the human eye.

In general: It might very well be that I did not tweak out the most perfect setting for all the augmentation bounds. I did not tune them a lot. Especially if you just care about performance on one dataset and not across CIFAR10/100/ImageNet/SVHN, you might be able to squeeze out more by changing these.

**Comment by jfltzngr** [comment]
Hi Samuel, 
Thanks for your reply. I will consider your recommendations! 
FYI: I did some tuning of the "ordinary" contrast for my problem. We could raise the accuracy by reducing the range to: MinMax(min=0.5, max=2.0). The previous max value completely greyed the image out (to the human eye).

**Comment by SamuelGabriel** [comment]
I see! Very interesting :) Good luck with your work.
